service:
  name: example-hello
#app: your-app-name
#tenant: your-tenant-name

plugins:
  - serverless-localstack
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

  region: ap-northeast-2

custom:
  localstack:
    stages:
      - local

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
